parameters:
    env(DB_HOST): '127.0.0.1'
    env(DB_DRIVER): 'mysql'
    env(DB_USER): 'user'
    env(DB_PASSWORD): 'user'
    env(DB_PORT): '3306'
    env(DB_NAME): 'elasticms'
    env(DB_SERVER_VERSION): '5.7'
    #env(DB_CHARSET): 'utf8mb4'

doctrine:
    dbal:
        # configure these for your database server
        #driver: 'pdo_%env(resolve:DB_DRIVER)%'
        server_version: '%env(resolve:DB_SERVER_VERSION)%'
        #charset: '%env(resolve:DB_CHARSET)%'
        #default_table_options:
            #charset: '%env(resolve:DB_CHARSET)%'
            #collate: '%env(resolve:DB_CHARSET)%_unicode_ci'

        url: '%env(resolve:DB_DRIVER)%://%env(resolve:DB_USER)%:%env(resolve:DB_PASSWORD)%@%env(resolve:DB_HOST)%:%env(resolve:DB_PORT)%/%env(resolve:DB_NAME)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
