parameters:
    env(DB_DRIVER): 'mysql'

doctrine_migrations:
    migrations_paths:
        Application\Migrations: '%kernel.project_dir%/src/Migrations/pdo_%env(resolve:DB_DRIVER)%'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
