parameters:
    env(EMSCH_INSTANCE_ID): website_
    env(EMSCH_ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(EMSCH_LIVE_INDEX): live
    env(EMSCH_PREVIEW_INDEX): preview
    env(EMSCH_PREVIEW_REGEX): '/preview/'
    env(EMSCH_TRANSLATION_TYPE): label
    env(EMSCH_TEMPLATES): '{"template": {"name": "key","code": "body"}, "routing": {"name": "content_type","code": "body"}}'
    env(EMSCH_ROUTES): '{}'

ems_client_helper:
    request_environments:
        preview:
           regex: '%env(string:EMSCH_PREVIEW_REGEX)%'
           index: '%env(string:EMSCH_PREVIEW_INDEX)%'
           backend: '%env(string:EMSCH_BACKEND_URL)%'
        live:
           regex: '/.*/'
           index: '%env(string:EMSCH_LIVE_INDEX)%'

    elasticms:
        website:
            hosts: '%env(json:EMSCH_ELASTICSEARCH_CLUSTER)%'
            index_prefix: '%env(string:EMSCH_INSTANCE_ID)%'
            translation_type: '%env(string:EMSCH_TRANSLATION_TYPE)%'
            templates: '%env(json:EMSCH_TEMPLATES)%'
            routes: '%env(json:EMSCH_ROUTES)%'

    language_selection:
        client_request: website
        template: '@EMSCH/template/language_select.html.twig'
        option_type: option
        supported_locale:
            - {locale: 'nl', logo_path: 'apple-touch-icon.png'}
            - {locale: 'fr', logo_path: 'apple-touch-icon.png'}

    routing:
        client_request: website
        redirect_type: 'redirect'
        relative_paths: ~