parameters:
    env(EMSCH_INSTANCE_ID): website_
    env(EMSCH_ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(EMSCH_BACKEND_URL): ~
    env(EMSCH_LOCALES): '["fr","nl"]'
    env(EMSCH_ENVS): '{}'

    env(EMSCH_ROUTE_TYPE):       ~
    env(EMSCH_TRANSLATION_TYPE): label
    env(EMSCH_ASSET_CONFIG_TYPE): ~
    env(EMSCH_TEMPLATES): '{}'
    env(EMSCH_ROUTES): '{}'

    env(EMSCH_SEARCH_TYPES):    '[]'
    env(EMSCH_SEARCH_FACETS):   '[]'
    env(EMSCH_SEARCH_SYNONYMS): '[]'
    env(EMSCH_SEARCH_FIELDS):   '[]'

    env(EMSCH_TEMPLATE_LANGUAGE): ~
    env(EMSCH_TEMPLATE_SEARCH):   ~
    env(EMSCH_TEMPLATE_ERROR):    ~
    env(EMSCH_TEMPLATE_EMS_LINK): '@@EMSCH/template/{type}.ems_link.twig'

    env(EMSCH_REDIRECT_TYPE): ~

    env(EMSCH_DUMP_ASSETS): true
ems_client_helper:
    locales: '%env(json:EMSCH_LOCALES)%'
    request_environments: '%env(json:EMSCH_ENVS)%'
    dump_assets: '%env(bool:EMSCH_DUMP_ASSETS)%'
    elasticms:
        website:
            hosts: '%env(json:EMSCH_ELASTICSEARCH_CLUSTER)%'
            index_prefix: '%env(string:EMSCH_INSTANCE_ID)%'
            route_type: '%env(string:EMSCH_ROUTE_TYPE)%'
            translation_type: '%env(string:EMSCH_TRANSLATION_TYPE)%'
            asset_config_type: '%env(string:EMSCH_ASSET_CONFIG_TYPE)%'
            templates: '%env(json:EMSCH_TEMPLATES)%'
            search:
                types:         '%env(json:EMSCH_SEARCH_TYPES)%'
                facets:        '%env(json:EMSCH_SEARCH_FACETS)%'
                synonyms:      '%env(json:EMSCH_SEARCH_SYNONYMS)%'
                fields:        '%env(json:EMSCH_SEARCH_FIELDS)%'

    templates:
        language: '%env(string:EMSCH_TEMPLATE_LANGUAGE)%'
        search:   '%env(string:EMSCH_TEMPLATE_SEARCH)%'
        error:    '%env(string:EMSCH_TEMPLATE_ERROR)%'
        ems_link:  '%env(string:EMSCH_TEMPLATE_EMS_LINK)%'
    routing:
        client_request: website
        routes: '%env(json:EMSCH_ROUTES)%'
        redirect_type: '%env(string:EMSCH_REDIRECT_TYPE)%'