twig_list:
    resource: '@EMSClientHelperBundle/Resources/config/routing/twig_list.xml'
    prefix: /_emsch

ems_form:
    resource: '@EMSFormBundle/Resources/config/routing/dev.xml'
    prefix: /_emsf