#home:
#    path: '/'
#    type: 'page'
#    query: '{"query": {"term": {"key": "Homepage"}}}'

service:
    type: 'service'
    path: '/{_locale}/service/{slug}'
    query: '{"query": {"term": {"slug_%_locale%": "%slug%"}}}'
    requirements:
        _locale: 'fr|nl'
    template: '@EMSCH/template/service.html.twig'

page:
    type: 'page'
    path: '/{_locale}/{slug}'
    query: '{"query": {"term": {"slug_%_locale%": "%slug%"}}}'
    requirements:
        _locale: 'fr|nl'
    template: '[template]'