services:
    EMS\CommonBundle\Storage\Adapter\HttpAdapter:
        tags: [ems_common.storage.adapter]
        arguments:
            - '%storage_path%'
            - '%env(string:EMSCH_BACKEND_URL)%'
            - '%env(string:EMSCH_API_KEY)%'
